AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Description: >
  s3-thumbnail-generator
  Sample SAM Template for s3-thumbnail-generator

Globals:
  Function:
    Timeout: 30
    Environment:
      Variables:
        THUMBNAIL_SIZE: 10
        REGION_NAME: "ap-south-1"
        BUCKET_NAME: !Sub "${AWS::StackName}-${AWS::Region}-${AWS::AccountId}"

Resources:
  S3ThumbnailGeneratorBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Sub "${AWS::StackName}-${AWS::Region}-${AWS::AccountId}" # #TOASK: Is setting bucket name like this the right way to do?

  GenerateThumbnailFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: handlers/
      Handler: app.generateThumbnail
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Policies: # Policy to allow the function to upload to the same S3 bucket
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action: "s3:*"
              Resource: "*"
      Events:
        S3ObjectCreatedEvent:
          Type: S3
          Properties:
            Bucket: !Ref S3ThumbnailGeneratorBucket
            Events:
              - "s3:ObjectCreated:*"

Outputs:
  # #TOASK: The below commented stuff was there in the HelloWorld template but that was causing some error for me. So like what are they and what do we use them for?
  # S3ObjectCreatedApi:
  #   Description: "API Gateway endpoint URL for Prod stage for GenerateThumbnailFunction function"
  #   Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/objectCreated/"
  GenerateThumbnailFunction:
    Description: "S3 Object creation trigger Lambda Function ARN"
    Value: !GetAtt GenerateThumbnailFunction.Arn
  # GenerateThumbnailFunctionIamRole:
  #   Description: "Implicit IAM Role created for Generate Thumbnail function"
  #   Value: !GetAtt GenerateThumbnailFunctionIamRole.Arn
